name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rsync files to VPS
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: "-avzr --delete --exclude=.env --exclude=venv"
          path: "./"
          remote_path: "/root/tameri/projects/study/dev/code/"
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
        env:
          RSYNC_LOG: "true"

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connexion au serveur VPS..."
            cd /root/tameri/projects/study/dev/code
            echo "Changement de répertoire effectué : $(pwd)"
            source venv/bin/activate || (python3 -m venv venv && source venv/bin/activate)
            pip install --upgrade pip
            pip install -r requirements.txt
            pip uninstall fitz PyMuPDF -y
            pip install PyMuPDF pytesseract
            echo "Redémarrage du service study..."
            sudo systemctl restart study.service
            echo "Déploiement terminé."